services:
  smallcap-signal:
    build: .
    ports:
      - "8123:8123"  # Expose port 8123 for the backend service
    environment:
      - API_KEY=${API_KEY}  # This will pull from the .env file
    volumes:
      - ./backend:/app/backend
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - frontend  # Same network as Nginx Proxy Manager
    restart: always

networks:
  frontend:
    external: true  # Ensure this matches an existing external network
